name: ThrowingStones
description: Throw items such as cobble and bricks as projectiles inflicting damage and effects
version: 0.0.4
author: Ben Sergent V

main: com.sergenttech.plugins.throwingstones.ThrowingStones
database: false